### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by DevinKreuzer** [graphdeeplearning/graphtransformer#1]
Hi, thanks for the great paper :)

I was just curious as to what the 'z' variable is in line 59 of the graph_transformer_layer.py code? I cannot seem to find the equivalent in the paper. It seems you are normalizing the output heads by the sum of the attention weights?

Would appreciate a little point :)

Thanks, 
Devin

**Comment by vijaydwivedi75** [comment]
Hi @DevinKreuzer, glad and thanks for your question.
We follow the DGL implementation with builtin funcs as described in detail [here](https://docs.dgl.ai/tutorials/models/4_old_wines/7_transformer.html#sphx-glr-tutorials-models-4-old-wines-7-transformer-py).

The 'z' is part of the softmax, implemented in [this fashion](https://docs.dgl.ai/tutorials/models/4_old_wines/7_transformer.html#speeding-up-with-built-in-functions).

Hope the article referenced makes clear and leaves no inconsistency as compared to the equations in the paper.

Cheers,
Vijay

**Comment by vijaydwivedi75** [comment]
Closing the issue!
Feel free to open in case of further questions.
