### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/molecules/ZINC.pkl'

### ISSUE THREAD

**Issue by gaoliming123** [graphdeeplearning/graphtransformer#10]
I run the command:
```
python main_molecules_graph_regression.py --config 'configs/molecules_GraphTransformer_LapPE_ZINC_500k_sparse_graph_BN.json' # for CPU
```
but get this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/molecules/ZINC.pkl'
```
where i can download the file

**Comment by vijaydwivedi75** [comment]
Hi @gaoliming123,
Use the instruction [at this step](https://github.com/graphdeeplearning/graphtransformer#2-download-datasets) to download the datasets, and then run the command.
