### ISSUE TITLE
Graph Classification

### ISSUE THREAD

**Issue by MichaelFu1998-create** [graphdeeplearning/graphtransformer#14]
Hello there, 
First of all, thank you for providing such an amazing work.
I'd like to know how can I leverage graphtransformer on Graph Classification task with textual data, for instance, I first extract nodes and edge info from the text data, given node features and edge information (only one type of edge in my case), the model generate binary targets based on those given features.

Kind Regards
Michael

**Comment by vijaydwivedi75** [comment]
Hi @MichaelFu1998-create,

For graph classification, you may follow the codes of ZINC. For ZINC, it predicts 1 label for the value being regressed. You may change the loss functions for your case. 

To prepare DGL graphs to be compatible with this code base, you can prepare your data following similar code [as that of ZINC](https://github.com/graphdeeplearning/graphtransformer/blob/main/data/molecules.py), for instance.

**Comment by MichaelFu1998-create** [comment]
No problem, really appreciate your clarification 👍
