### ISSUE TITLE
AttributeError: Can't get attribute 'DGLHeteroGraph' on <module 'dgl.heterograph' >

### ISSUE THREAD

**Issue by RodyCoco** [graphdeeplearning/graphtransformer#26]
Hi, I try to run the example code "main_SBMs_node_classification.py" by the following command:

` python main_SBMs_node_classification.py --gpu_id 0 --config 'configs/SBMs_GraphTransformer_CLUSTER_500k_full_graph_BN.json'`

But it comes with the following error:
`AttributeError: Can't get attribute 'DGLHeteroGraph' on <module 'dgl.heterograph' from '/home/rody/.local/share/virtualenvs/rody-V7qEFACp/lib/python3.6/site-packages/dgl/heterograph.py'>`

How can I fix this bug, thanks!

**Comment by RodyCoco** [comment]
I fix it by remove dgl and install dgl(cuda version) because I run with gpu.

**Comment by fei-wang-1314** [comment]
https://blog.csdn.net/weixin_39554819/article/details/128569482

该方法可以用，已测。

**Comment by BodongDu** [comment]
I remove dgl and installed dgl 1.1.2+cu118 dglgo 0.0.2(cuda version==12.2), but it still comes with the following errors: cuda available with GPU: NVIDIA GeForce RTX 3090
[I] Loading dataset SBM_CLUSTER...
Traceback (most recent call last):
  File "/home/zbh/whd/benchmarking-gnns-master/main_SBMs_node_classification.py", line 428, in <module>
    main()    
  File "/home/zbh/whd/benchmarking-gnns-master/main_SBMs_node_classification.py", line 318, in main
    dataset = LoadData(DATASET_NAME)
  File "/home/zbh/whd/benchmarking-gnns-master/data/data.py", line 38, in LoadData
    return SBMsDataset(DATASET_NAME)
  File "/home/zbh/whd/benchmarking-gnns-master/data/SBMs.py", line 160, in __init__
    f = pickle.load(f)
AttributeError: Can't get attribute 'DGLHeteroGraph' on <module 'dgl.heterograph' from '/home/zbh/.conda/envs/dgl/lib/python3.9/site-packages/dgl/heterograph.py'>. How can I fix this bug, thx!

**Comment by BodongDu** [comment]
Maybe the .pkl file version is not compatible with the newest version of dgl??
