### ISSUE TITLE
about attention

### ISSUE THREAD

**Issue by lao-sheng** [graphdeeplearning/graphtransformer#5]
![图片](https://user-images.githubusercontent.com/59272013/107838982-c11f7480-6de3-11eb-8318-8b7e3c9790bb.png)
![图片](https://user-images.githubusercontent.com/59272013/107839065-633f5c80-6de4-11eb-9468-db7be822e1e5.png)
Hello, about the problem of calculating attention, the attention of node i and its adjacent nodes is calculated in the formula, but I find that the final calculation is the attention of all nodes, and it does not distinguish whether the nodes are connected. Is there a problem with my understanding?

**Comment by vijaydwivedi75** [comment]
Hi @lao-sheng,

The code section you highlight give the outputs of Q, K, V projections.

The implementation for node to attend to its local neighborhood is carried out by this function, which is just followed after the projections.
https://github.com/graphdeeplearning/graphtransformer/blob/3c83b4ba5e45a2e25bbefde1b35d88a27ca3cfb2/layers/graph_transformer_layer.py#L73

https://github.com/graphdeeplearning/graphtransformer/blob/3c83b4ba5e45a2e25bbefde1b35d88a27ca3cfb2/layers/graph_transformer_layer.py#L51-L59

**Comment by lao-sheng** [comment]
oh,i see.thanks！
