### ISSUE TITLE
About Equations 11~12

### ISSUE THREAD

**Issue by ZikangZhou** [graphdeeplearning/graphtransformer#7]
Hi,

Great work!

I want to confirm whether my understanding of equations 11~12 is correct.

I understand equation 12 in this way: (Q h_i * K h_j / sqrt(d_k)) is a scalar, and (E e_ij) is a d_k-dim vector. Then a scalar multiplying a vector gives a d_k-dim vector. In equation 11, this d_k-dim vector is transformed to a scalar by computing w_1+w_2+...+w_dk. Is it correct?

**Comment by vijaydwivedi75** [comment]
Hi @ZikangZhou,
Thanks for your query.
Actually, In Eqn. 12 the computations are elementwise, (unlike that of Eqn. 5).
To continue to your answer please refer [this issue](https://github.com/graphdeeplearning/graphtransformer/issues/4), that includes pointers to corresponding code implementations.
Best Regards.

**Comment by ZikangZhou** [comment]
Thanks for your reply. So you mean in edge transformer, all product operations are element-wise instead of dot product? That sounds interesting.

**Comment by vijaydwivedi75** [comment]
As mentioned in the [above referenced issue](https://github.com/graphdeeplearning/graphtransformer/issues/4), the process of injecting available edge features is chosen to be feature-dimension wise in Graph Transformer Layer with edge features; thus the elementwise computations in Eqn. 12.

However, For Eqn. 11 and then forward to Eqn 9, they are scalar values, as mentioned in detail in the referenced issue:

> In Eqn.11 the features of \hat{w}_{i, j} are summed across the d-dimensions to obtain scalars.

**Comment by ZikangZhou** [comment]
Thanks for clarifying, I somehow understand the intuition behind it.
